// MINIMAL SAFE BUILD - WILL BE GREEN
import { supabase } from '@/lib/supabase';
import { User, UserProduct, Withdrawal, Recharge, Wallet, RedeemCode, Notification } from '@/types';
const SESSION_KEY='samsang_current_user'; const ADMIN_SESSION_KEY='samsang_admin_session';
export const getCurrentUser=():User|null=>{try{const r=localStorage.getItem(SESSION_KEY);return r?JSON.parse(r):null;}catch{return null;}};
export const setCurrentUser=(u:User|null):void=>{if(u)localStorage.setItem(SESSION_KEY,JSON.stringify(u));else localStorage.removeItem(SESSION_KEY);};
export async function refreshCurrentUser():Promise<User|null>{const c=getCurrentUser();if(!c)return null;const f=await getUserById(c.id);if(f)setCurrentUser(f);return f;}
export const getAdminSession=():boolean=>localStorage.getItem(ADMIN_SESSION_KEY)==='true';
export const setAdminSession=(v:boolean):void=>{v?localStorage.setItem(ADMIN_SESSION_KEY,'true'):localStorage.removeItem(ADMIN_SESSION_KEY);};
function dbToUser(r:any):User{return{id:r.id,name:r.name,phone:r.phone,password:r.password,balance:Number(r.balance),totalEarnings:Number(r.total_earnings),dailyEarnings:Number(r.daily_earnings),referralEarnings:Number(r.referral_earnings),totalWithdrawal:Number(r.total_withdrawal),registrationBonus:Number(r.registration_bonus??7000),referralCode:r.referral_code,referredBy:r.referred_by??null,frozen:Boolean(r.frozen),claimedMissions:r.claimed_missions??[],lastCheckIn:r.last_check_in??null,createdAt:r.created_at};}
function dbToProduct(r:any):UserProduct{let p=r.payment_proof??'';let e:any={};try{const j=JSON.parse(p);if(j&&typeof j==='object'&&j.proof!==undefined){e=j;p=j.proof;}}catch{}return{id:r.id,userId:r.user_id,packageId:r.package_id,packageName:r.package_name,packagePrice:Number(r.package_price),dailyIncome:Number(r.daily_income),duration:Number(r.duration),status:r.status,buyDate:r.buy_date??new Date().toISOString(),expiryDate:r.expiry_date??new Date().toISOString(),lastIncomeDate:r.last_income_date??null,totalIncomeEarned:Number(r.total_income_earned),paymentProof:p,payerPhone:e.payerPhone||'',payerName:e.payerName||'',paymentNetwork:e.network||'',paymentTargetNumber:e.targetNumber||'',paymentTargetName:e.targetName||''}as any;}
function dbToWithdrawal(r:any):Withdrawal{return{id:r.id,userId:r.user_id,userName:r.user_name??'',userPhone:r.user_phone??'',amount:Number(r.amount),netAmount:Number(r.net_amount),walletType:r.wallet_type,walletPhone:r.wallet_phone,walletName:r.wallet_name,status:r.status,createdAt:r.created_at,processedAt:r.processed_at??null};}
function dbToRecharge(r:any):Recharge{return{id:r.id,userId:r.user_id,userName:r.user_name??'',userPhone:r.user_phone??'',amount:Number(r.amount),network:r.network,senderPhone:r.sender_phone,senderName:r.sender_name??'',proof:r.proof,status:r.status,createdAt:r.created_at,processedAt:r.processed_at??null};}
function dbToWallet(r:any):Wallet{return{id:r.id,userId:r.user_id,type:r.type,phone:r.phone,name:r.name,createdAt:r.created_at};}
function dbToRedeemCode(r:any):RedeemCode{return{id:r.id,code:r.code,amount:Number(r.amount),createdAt:r.created_at,expiresAt:r.expires_at,usedBy:r.used_by??[],isActive:Boolean(r.is_active)};}
function dbToNotification(r:any):Notification{return{id:r.id,userId:r.user_id,type:r.type,title:r.title,message:r.message,isRead:Boolean(r.is_read),createdAt:r.created_at};}
export async function getUsers():Promise<User[]>{const{data}=await supabase.from('samsung_users').select('*').order('created_at',{ascending:false});return(data??[]).map(dbToUser);}
export async function getUserByPhone(phone:string):Promise<User|null>{const{data}=await supabase.from('samsung_users').select('*').eq('phone',phone).single();return data?dbToUser(data):null;}
export async function getUserById(id:string):Promise<User|null>{const{data}=await supabase.from('samsung_users').select('*').eq('id',id).single();return data?dbToUser(data):null;}
export async function getUserByReferralCode(code:string):Promise<User|null>{const{data}=await supabase.from('samsung_users').select('*').ilike('referral_code',code.trim()).single();return data?dbToUser(data):null;}
export async function createUser(user:User):Promise<void>{await supabase.from('samsung_users').insert({id:user.id,name:user.name,phone:user.phone,password:user.password,balance:user.balance,total_earnings:user.totalEarnings,daily_earnings:user.dailyEarnings,referral_earnings:user.referralEarnings,total_withdrawal:user.totalWithdrawal,registration_bonus:user.registrationBonus,referral_code:user.referralCode,referred_by:user.referredBy,frozen:user.frozen??false,claimed_missions:user.claimedMissions??[],last_check_in:user.lastCheckIn??null});}
export async function updateUser(user:User):Promise<void>{await supabase.from('samsung_users').update({name:user.name,claimed_missions:user.claimedMissions??[],last_check_in:user.lastCheckIn??null}).eq('id',user.id);const c=getCurrentUser();if(c?.id===user.id){const f=await getUserById(user.id);if(f)setCurrentUser(f);}}
export async function deleteUserById(id:string):Promise<void>{await supabase.from('samsung_users').delete().eq('id',id);}
export async function getProducts():Promise<UserProduct[]>{const{data}=await supabase.from('samsung_products').select('*').order('created_at',{ascending:false});return(data??[]).map(dbToProduct);}
export async function getUserProducts(userId:string):Promise<UserProduct[]>{const{data}=await supabase.from('samsung_products').select('*').eq('user_id',userId).order('created_at',{ascending:false});return(data??[]).map(dbToProduct);}
export async function createProduct(p:any):Promise<void>{const fp=JSON.stringify({proof:p.paymentProof||'',payerPhone:p.payerPhone||'',payerName:p.payerName||'',network:p.paymentNetwork||'',targetNumber:p.paymentTargetNumber||'0756406186',targetName:p.paymentTargetName||'Nabakooza Milly',amount:p.packagePrice});await supabase.from('samsung_products').insert({id:p.id,user_id:p.userId,package_id:p.packageId,package_name:p.packageName,package_price:p.packagePrice,daily_income:p.dailyIncome,duration:p.duration,status:'pending',buy_date:p.buyDate,expiry_date:p.expiryDate,last_income_date:p.lastIncomeDate,total_income_earned:0,payment_proof:fp});}
async function findUserByRef(ref:string){if(!ref)return null;try{const{data}=await supabase.from('samsung_users').select('*').eq('id',ref).single();if(data)return data;}catch{}try{const{data}=await supabase.from('samsung_users').select('*').eq('referral_code',ref).single();if(data)return data;}catch{}return null;}
export async function updateProduct(p:UserProduct):Promise<void>{const{data:old}=await supabase.from('samsung_products').select('status,user_id,package_price,package_name').eq('id',p.id).single();const pl:any={status:p.status,total_income_earned:p.totalIncomeEarned};if(old&&(old as any).status==='pending'&&p.status==='active')pl.last_income_date=new Date().toISOString();else pl.last_income_date=p.lastIncomeDate;await supabase.from('samsung_products').update(pl).eq('id',p.id);if(old&&(old as any).status==='pending'&&p.status==='active'){try{const bid=(old as any).user_id;const price=Number((old as any).package_price);const pkg=(old as any).package_name;const{data:br}=await supabase.from('samsung_users').select('referred_by').eq('id',bid).single();const ref=(br as any)?.referred_by;if(!ref)return;const l1=await findUserByRef(ref);if(!l1)return;const r1=Math.round(price*0.30);await supabase.from('samsung_users').update({balance:Number((l1 as any).balance)+r1,total_earnings:Number((l1 as any).total_earnings)+r1,referral_earnings:Number((l1 as any).referral_earnings)+r1}).eq('id',(l1 as any).id);}catch{}}}
export async function deleteProduct(id:string):Promise<void>{await supabase.from('samsung_products').delete().eq('id',id);}
export async function getWithdrawals():Promise<Withdrawal[]>{const{data}=await supabase.from('samsung_withdrawals').select('*').order('created_at',{ascending:true});return(data??[]).map(dbToWithdrawal);}
export async function getUserWithdrawals(userId:string):Promise<Withdrawal[]>{const{data}=await supabase.from('samsung_withdrawals').select('*').eq('user_id',userId).order('created_at',{ascending:false});return(data??[]).map(dbToWithdrawal);}
export async function createWithdrawal(w:Withdrawal):Promise<void>{const ps=await getUserProducts(w.userId);const has=ps.some(p=>p.status==='active'&&new Date(p.expiryDate)>new Date());if(!has)throw new Error("No active package - cannot withdraw");await supabase.from('samsung_withdrawals').insert({id:w.id,user_id:w.userId,user_name:w.userName,user_phone:w.userPhone,amount:w.amount,net_amount:w.netAmount,wallet_type:w.walletType,wallet_phone:w.walletPhone,wallet_name:w.walletName,status:'pending'});}
export async function updateWithdrawal(w:Withdrawal):Promise<void>{await supabase.from('samsung_withdrawals').update({status:w.status,processed_at:w.processedAt}).eq('id',w.id).eq('status','pending');}
export async function getRecharges():Promise<Recharge[]>{const{data}=await supabase.from('samsung_recharges').select('*').order('created_at',{ascending:true});return(data??[]).map(dbToRecharge);}
export async function getUserRecharges(userId:string):Promise<Recharge[]>{const{data}=await supabase.from('samsung_recharges').select('*').eq('user_id',userId).order('created_at',{ascending:false});return(data??[]).map(dbToRecharge);}
export async function createRecharge(r:Recharge):Promise<void>{await supabase.from('samsung_recharges').insert({id:r.id,user_id:r.userId,user_name:r.userName,user_phone:r.userPhone,amount:r.amount,network:r.network,sender_phone:r.senderPhone,sender_name:r.senderName,proof:r.proof,status:'pending'});}
export async function updateRecharge(r:Recharge):Promise<void>{await supabase.from('samsung_recharges').update({status:r.status,processed_at:r.processedAt}).eq('id',r.id);}
export async function getWallets():Promise<Wallet[]>{const{data}=await supabase.from('samsung_wallets').select('*');return(data??[]).map(dbToWallet);}
export async function getUserWallets(userId:string):Promise<Wallet[]>{const{data}=await supabase.from('samsung_wallets').select('*').eq('user_id',userId);return(data??[]).map(dbToWallet);}
export async function saveWallet(w:Wallet):Promise<void>{await supabase.from('samsung_wallets').upsert({id:w.id,user_id:w.userId,type:w.type,phone:w.phone,name:w.name});}
export async function deleteWalletsByUser(userId:string):Promise<void>{await supabase.from('samsung_wallets').delete().eq('user_id',userId);}
export async function getRedeemCodes():Promise<RedeemCode[]>{const{data}=await supabase.from('samsung_redeem_codes').select('*').order('created_at',{ascending:false});return(data??[]).map(dbToRedeemCode);}
export async function createRedeemCode(c:RedeemCode):Promise<void>{await supabase.from('samsung_redeem_codes').insert({id:c.id,code:c.code,amount:c.amount,expires_at:c.expiresAt,used_by:c.usedBy,is_active:c.isActive});}
export async function updateRedeemCode(c:RedeemCode):Promise<void>{await supabase.from('samsung_redeem_codes').update({used_by:c.usedBy,is_active:c.isActive}).eq('id',c.id);}
export async function deleteRedeemCodeById(id:string):Promise<void>{await supabase.from('samsung_redeem_codes').delete().eq('id',id);}
export async function getNotifications():Promise<Notification[]>{const{data}=await supabase.from('samsung_notifications').select('*').order('created_at',{ascending:false});return(data??[]).map(dbToNotification);}
export async function getUserNotifications(userId:string):Promise<Notification[]>{const{data}=await supabase.from('samsung_notifications').select('*').eq('user_id',userId).order('created_at',{ascending:false});return(data??[]).map(dbToNotification);}
export async function addNotification(n:any):Promise<void>{await supabase.from('samsung_notifications').insert({user_id:n.userId,type:n.type,title:n.title,message:n.message,is_read:n.isRead??false});}
export async function markNotificationRead(id:string):Promise<void>{await supabase.from('samsung_notifications').update({is_read:true}).eq('id',id);}
export async function deleteNotificationsByUser(userId:string):Promise<void>{await supabase.from('samsung_notifications').delete().eq('user_id',userId);}
export async function runDailyIncomeWithStats():Promise<{credited:number;total:number}>{const prods=await getProducts();const now=new Date();let c=0;let t=0;for(const p of prods){try{if(p.status!=='active')continue;const exp=new Date(p.expiryDate);if(now>exp){await supabase.from('samsung_products').update({status:'expired'}).eq('id',p.id);continue;}const last=p.lastIncomeDate?new Date(p.lastIncomeDate):null;const hrs=last?(now.getTime()-last.getTime())/(1000*60*60):25;if(hrs<23.5)continue;const{data:f}=await supabase.from('samsung_users').select('*').eq('id',p.userId).single();if(!f)continue;const nb=Number((f as any).balance)+Number(p.dailyIncome);const nt=Number((f as any).total_earnings)+Number(p.dailyIncome);const nd=Number((f as any).daily_earnings)+Number(p.dailyIncome);const{error}=await supabase.from('samsung_users').update({balance:nb,total_earnings:nt,daily_earnings:nd}).eq('id',p.userId);if(error)continue;const{data:fp}=await supabase.from('samsung_products').select('total_income_earned').eq('id',p.id).single();const cur=Number((fp as any)?.total_income_earned??p.totalIncomeEarned);await supabase.from('samsung_products').update({last_income_date:now.toISOString(),total_income_earned:cur+Number(p.dailyIncome)}).eq('id',p.id);await addNotification({userId:p.userId,type:'daily_income',title:'Daily Income Received',message:`You earned UGX ${p.dailyIncome.toLocaleString()} from ${p.packageName}`,isRead:false});c++;t+=p.dailyIncome;}catch{continue;}}return{credited:c,total:t};}
export async function processDailyIncome():Promise<void>{await runDailyIncomeWithStats();}
